[package]
name = "contract"
version = "0.11.0"
authors = ["Eugene The Dream"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
unc-sdk = "0.7.2"
unc-contract-standards = "0.7.2"
unc-sys = "0.1.0"
